HV-1854 Improve PESEL validator conditions
hibernate/hibernate-validator pull request #1184
Opened 2021-11-02 12:51 UTC by marko-bekhta

https://hibernate.atlassian.net/browse/HV-1854

With PESEL structure being YYMMDDZZZXQ only MM and DD parts make sense to have some additional checks applied. Year can be 00-99, ZZZ just "random digits", X - sex part is even/odd but ultimately 0-9 as well. 
Check digits in the new testcases would've allowed these numbers to be considered as valid without this additional date/month logic.

I'm actually glad that someone is using these specific validators and reported a problem with that more simple approach. 
But not as glad as being able to finally do some work here 😉

2021-11-03 11:09 UTC, turo-90 commented on engine/src/main/java/org/hibernate/validator/internal/constraintvalidators/hv/pl/PESELValidator.java
> +		int date = doubleDigitNumberFromSubList( digits, 4 );
you should check if a given month has this number of days

2021-11-05 10:16 UTC, gsmet requested changes
Hey Marko, glad to see you here :). I spotted a few minor things. 

The question of @turo-90 is interesting: I have no idea if PESEL enforces the fact that the day must exist for it to be valid. That's probably something to check before enforcing it as I could see people relying on this sort of weird behavior.

2021-11-05 10:29 UTC, turo-90 commented
> 
> 
> Hey Marko, glad to see you here :). I spotted a few minor things.
> 
> The question of @turo-90 is interesting: I have no idea if PESEL enforces the fact that the day must exist for it to be valid. That's probably something to check before enforcing it as I could see people relying on this sort of weird behavior.

The PESEL number must have a correct and existing date.
This is an identification number for people in Poland that includes their date of birth.

2021-11-11 08:48 UTC, turo-90 approved these changes

2021-11-11 08:49 UTC, turo-90 approved these changes

2021-11-11 12:45 UTC, gsmet approved these changes
Nice work.

2021-11-11 12:45 UTC, merged

2021-11-11 12:50 UTC, marko-bekhta commented
Hi Guillaume!!! Thanks! Glad to see that you all are still around! 
And thanks for taking a look at this one.

Will need to fix my email notifications as I've missed your original comment initially 🙈