HV-1863 Experiment with records in the annotation processor - 6.2
hibernate/hibernate-validator pull request #1249
Opened 2022-03-28 16:09 UTC by jrenaat

[(https://hibernate.atlassian.net/browse/HV-1863)](https://hibernate.atlassian.net/browse/HV-1863)

2022-03-28 16:11 UTC, jrenaat commented on engine/src/test/java17/org/hibernate/validator/test/constraints/records/RecordConstrainedTest.java
> +	public void byteBuddyRecordTest() {
I added this test, even if I didn't actually manage to get it to work; perhaps I'm not adding the validation annotation to the record class correctly, or in order for this 'hot swap' to work we would need a java agent?

2022-04-07 09:56 UTC, gsmet requested changes
Looks good, thanks. I added a few comments inline.

2022-05-04 10:09 UTC, gsmet approved these changes

2022-05-04 10:09 UTC, merged

2022-05-04 10:10 UTC, gsmet commented
I merged this, thanks. Gonna work on pushing it to the other branches now.

2022-05-26 21:34 UTC, ferdinand-swoboda commented
@gsmet Can you give an indication regarding when this change will be released 🙂 ? Thanks

2022-08-03 08:16 UTC, Katalystical commented
@gsmet @yrodiere Any chance for a new release? :-)

2022-08-03 09:25 UTC, gsmet commented
@Katalystical I will push one today.

2022-08-04 13:27 UTC, gsmet commented
@Katalystical sorry I got a bit sidetracked. 6.2.4.Final is available on Maven Central now.